### ISSUE TITLE
Finalize the Web scraping basics for Python devs course

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#1319]
Missing lessons:

- [x] DevTools 1: The Phantom Menace https://github.com/apify/apify-docs/pull/1316
- [x] DevTools 2: Attack of the Clones https://github.com/apify/apify-docs/pull/1317
- [x] DevTools 3: Revenge of the Sith https://github.com/apify/apify-docs/pull/1321
- [x] Using a framework https://github.com/apify/apify-docs/pull/1303
- [x] Using a platform https://github.com/apify/apify-docs/pull/1424, https://github.com/apify/apify-docs/pull/1556

What else needs to be done:

- [x] Unify tags and elements - in the Python lessons there's "Our code lists all `<h1>` tags", in the DevTools it's more like "`a` element" https://github.com/apify/apify-docs/pull/1558
- [x] DevTools 1 and 2: Product name vs product title https://github.com/apify/apify-docs/pull/1558
- [x] THAT LESSON in sentence "We will show you how scraping platforms can simplify your life, but those lessons are optional and designed to fit within our [free tier](https://apify.com/pricing)." https://github.com/apify/apify-docs/pull/1558
- [x] https://github.com/apify/apify-docs/issues/1417, https://github.com/apify/apify-docs/pull/1559
- [x] Provide a nicer, higher-resolution image here: https://github.com/apify/apify-docs/blob/1abc0eec1c4268b923281d433854d8b675b22e1a/sources/academy/webscraping/scraping_basics_python/index.md?plain=1#L24 https://github.com/apify/apify-docs/pull/1559
- [x] Final reading, make the course coherent in style, admonitions, etc. https://github.com/apify/apify-docs/pull/1568
    - [x] Unify WE vs YOU. I think the lesson should be WE, and the exercises should be YOU.
    - [x] Make super sure the transition from DevTools to Python is smooth (codename: Star Wars prequel trilogy problem)
    - [x] Add info about how what you see in DevTools is **NOT** what you get in Python unless you spin up a browser
- [x] verify exercise at academy/scraping-basics-python/parsing-html (comment reporting its broken)
- [x] Reconsider adding type hints, at least for context in the framework lesson https://github.com/apify/apify-docs/pull/1303#pullrequestreview-2473520225, https://github.com/apify/apify-docs/pull/1562
- [x] Make the Python course more prominent in the Academy menu and homepage https://github.com/apify/apify-docs/pull/1571

Future considerations (unordered):

- [ ] ~~Add a final exercise which will interact with the datasets using the SDK (see below)~~ https://github.com/apify/apify-docs/issues/1570
- [x] Rename the JavaScript course to "Web scraping basics for JavaScript devs" https://github.com/apify/apify-docs/pull/1551
- [x] Try removing sidebar position to have cleaner front matter https://github.com/apify/apify-docs/issues/1247, https://github.com/apify/apify-docs/pull/1557
- [ ] ~~test exercises~~ https://github.com/apify/apify-docs/issues/1243

Final exercise:

- [ ] ~~single final exercise: build an app to analyze data from several runs, e.g. print price trend of a certain product (sony subwoofer?)~~ https://github.com/apify/apify-docs/issues/1570
