### ISSUE TITLE
Update the "Actors" section after the UI redesign

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-docs#183]
This will involve:
- [x] update all the screenshots to reflect the new UI
- [x] remove content that is already in the SDK and replacing with links / move to SDK what should be there
- [x] add links to SDK that should be linked
- [ ] restructure the section where needed
 - [x] make sure all internal processes are linked
